### ISSUE TITLE
Typescript Module Declaration Support

### ISSUE THREAD

**Issue by harrydrippin** [lablup/backend.ai-client-js#6]
Hello, 

I made very abstract and simple type declaration for Typescript support of this library, and now our company, Common Computer, using this in our company on the internal project.

This file currently contains some of `any` types and unclear typings, but I can just run the module and adapt this module to our project.

If you agree for including this declaration file to your repository, I will gladly open the pull request and handle this issue.

Thank you for your support!

**Comment by harrydrippin** [comment]
And I implemented a very small 2-line function for fetching specific kernel's information by session ID, which was not contained in this repository. If you want, I will make another PR for this.

**Comment by inureyes** [comment]
@harrydrippin Pull request is welcomed! 👍

**Comment by inureyes** [comment]
Some methods about graphQL requests are missing in declaration, but graphQL-based features are still in development and are not important at this time. Good job!
